#!/bin/bash

# Ensure the script is executable
chmod +x bash_script.sh

# Compile the program
make

# First run with a, b, c = 3
echo "Running with a=3, b=3, c=3"
make run ARGS="11 1000 1e-6"

# Second run with a, b, c = 5
#echo "Running with a=5, b=5, c=5"
#make run ARGS="51 5000 1e-5"